#! /bin/bash

export VERSION="46"
export SYSTEM_DESC="ChimeraOS"
export SYSTEM_NAME="chimeraos"
export USERNAME="gamer"
export SIZE="12000MB"
export WEBSITE="https://chimeraos.org"
export DOCUMENTATION_URL="https://chimeraos.org/about"
export BUG_REPORT_URL="https://github.com/ChimeraOS/chimeraos/issues"

export KERNEL_PACKAGE="linux-chimeraos"
export KERNEL_PACKAGE_ORIGIN="local"

# Chimera Self-Built Package
export PACKAGES="\
	linux-chimeraos \
	linux-chimeraos-headers \
	lib32-libva-mesa-driver \
	lib32-mesa \
	lib32-mesa-vdpau \
	lib32-opencl-rusticl-mesa \
	lib32-vulkan-intel \
	lib32-vulkan-mesa-layers \
	lib32-vulkan-radeon \
	lib32-vulkan-nouveau \
	lib32-vulkan-swrast \
	libva-mesa-driver \
	mesa \
	mesa-vdpau \
	opencl-rusticl-mesa \
	vulkan-intel \
	vulkan-mesa-layers \
	vulkan-radeon \
	vulkan-nouveau \
	vulkan-swrast \
"

export PACKAGES="$PACKAGES \
	accountsservice \
	acpi_call-dkms \
	alsa-firmware \
	alsa-utils \
	amd-ucode \
	ark \
	bash-completion \
	bluedevil \
	breeze-gtk \
	broadcom-wl-dkms \
	bzip2 \
	cage \
	cifs-utils \
	cpupower \
	diffutils \
	dkms \
	discover \
	distrobox \
	dmidecode \
	dosbox \
	dolphin \
	dolphin-plugins \
	efibootmgr \
	ethtool \
	evtest \
	expect \
	exfatprogs \
	fcitx5-breeze \
	fcitx5-chinese-addons \
	fcitx5-im \
	fcitx5-pinyin-zhwiki \
	ffmpeg \
	ffmpegthumbnailer \
	file \
	firefox \
	firejail \
	flatpak \
	flatpak-kcm \
	fmt \
	fuse-zip \
	fuse2 \
	fwupd \
	gamescope \
	git \
	grml-zsh-config \
	gst-plugin-pipewire \
	gvfs-smb \
	gvfs-nfs \
	gzip \
	haveged \
	htop \
	iio-sensor-proxy \
	intel-gpu-tools \
	intel-media-driver \
	intel-ucode \
	intel-undervolt \
	jq \
	kate \
	kde-gtk-config \
	kdeconnect \
	kdeplasma-addons \
	kfind \
	kgamma \
	kinfocenter \
	konsole \
	kpipewire \
	kscreen \
	ksshaskpass \
	kwalletmanager \
	kwallet-pam \
	less \
	lib32-curl \
	lib32-fontconfig \
	lib32-freetype2 \
	lib32-libgpg-error \
	lib32-libnm \
	lib32-libxinerama \
	lib32-libxcrypt-compat \
	lib32-libva \
	lib32-libva-intel-driver \
	lib32-libva-vdpau-driver \
	lib32-openal \
	lib32-pipewire \
	lib32-sdl2 \
	lib32-systemd \
	lib32-vulkan-icd-loader \
	libcurl-gnutls \
	libidn11 \
	libva-vdpau-driver \
	libva-intel-driver \
	libxcrypt-compat \
	libxss \
	linux-firmware \
	liquidctl \
	logrotate \
	lrzip \
	lshw \
	maliit-keyboard \
	modemmanager \
	nano \
	networkmanager \
	nfs-utils \
	noto-fonts-cjk \
	noto-fonts-emoji \
	nss-mdns \
	openal \
	openssh \
	p7zip \
	pipewire \
	pipewire-alsa \
	pipewire-jack \
	pipewire-pulse \
	plasma-browser-integration \
	plasma-desktop \
	plasma-disks \
	plasma-nm \
	plasma-pa \
	plasma-thunderbolt \
	plasma-vault \
	podman \
	pulsemixer \
	python \
	python-inotify-simple \
	python-notify2 \
	rsync \
	sddm \
	smbclient \
	sof-firmware \
	sshfs \
	steam \
	sudo \
	tar \
	tree \
	ttf-droid \
	ttf-liberation \
	unace \
	unrar \
	unzip \
	usb_modeswitch \
	usbutils \
	vim \
	vulkan-icd-loader \
	wavpack \
	wget \
	which \
	wireplumber \
	wqy-zenhei \
	xdg-desktop-portal \
	xdg-desktop-portal-gtk \
	xdg-desktop-portal-kde \
	xdg-desktop-portal-wlr \
	xdg-user-dirs-gtk \
	xf86-video-amdgpu \
	xorg-server \
	xorg-server-xvfb \
	xorg-xinit \
	xsettingsd \
	xz \
	zip \
	zsh \
	zsh-autosuggestions \
	zsh-completions \
	zsh-syntax-highlighting \
"

export AUR_PACKAGES="\
	ayaneo-platform-dkms-git \
	ayn-platform-dkms-git \
	bcm20702a1-firmware \
	bmi160-aya-neo-dkms-git \
	bmi260-dkms \
	boxtron \
	downgrade \
	evdev-keepalive \
	frzr \
	gamescope-session-steam-git \
	hhd \
	hhd-user \
	hhfc-git \
	legendary \
	lib32-extest \
	lib32-gperftools \
	kanit-font \
	nintendo-udev \
	paru-bin \
	protonup-qt-bin \
	python-vdf \
	r8152-dkms \
	rtl8812au-dkms-git \
	rtl8814au-dkms-git \
	rtl88x2bu-dkms-git \
	rtl8821au-dkms-git \
	ryzenadj-git \
	steam_notif_daemon \
	steam-powerbuttond-git \
	steam-removable-media-git \
	wyvern \
	waydroid \
	waydroid-script-git \
	wlr-randr \
	zenergy-dkms-git \
"
export PACKAGES="$PACKAGES $AUR_PACKAGES"

export SERVICES="\
	NetworkManager \
	avahi-daemon \
	bluetooth \
	bluetooth-workaround \
	fstrim.timer \
	haveged \
	hhd@gamer \
	home-swapfile.swap \
	sddm \
	steam-powerbuttond \
	sshd \
	systemd-timesyncd \
	swapfile \
	waydroid-container \
"

export USER_SERVICES="\
	pipewire \
"

export FILES_TO_DELETE="\
	/boot/initramfs-linux-fallback.img \
	/usr/share/SFML \
	/usr/share/doc \
	/usr/share/gtk-doc \
	/usr/share/help \
	/usr/share/man \
"

postinstallhook() {
	# override steamos-update
	mv /usr/bin/steamos-update /usr/bin/steamos-update.ori
	ln -s /usr/bin/steamos-update-override /usr/bin/steamos-update

	# Add sudo permissions
	sed -i '/%wheel ALL=(ALL:ALL) ALL/s/^# //g' /etc/sudoers
	echo "${USERNAME} ALL=(ALL) NOPASSWD:ALL" > "/etc/sudoers.d/${USERNAME}"

	echo "source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
" >>/etc/zsh/zshrc

	# download and add racing wheel udev rules
	pushd /usr/lib/udev/rules.d
	curl -L -O https://raw.githubusercontent.com/berarma/oversteer/master/data/udev/99-fanatec-wheel-perms.rules
	curl -L -O https://raw.githubusercontent.com/berarma/oversteer/master/data/udev/99-logitech-wheel-perms.rules
	curl -L -O https://raw.githubusercontent.com/berarma/oversteer/master/data/udev/99-thrustmaster-wheel-perms.rules
	popd

	# Remove build tools for slimmer image
	# rm /usr/share/libalpm/hooks/70-dkms-install.hook
	# rm /usr/share/libalpm/hooks/70-dkms-upgrade.hook
	# rm /usr/share/libalpm/hooks/71-dkms-remove.hook
	# pacman --noconfirm -Rnsdd make gcc dkms ${KERNEL_PACKAGE}-headers

	# clean up desktop shortcuts
	sed -i -e 's/Name=Steam (Runtime)/Name=Steam/' /usr/share/applications/steam.desktop

	# use script to fix steam input in wayland mode
	sed -i 's,Exec=/usr/bin/steam-runtime,Exec=/usr/bin/steam-desktop-mode,' /usr/share/applications/steam.desktop

	# set permissions for intel_gpu_top and mangohud
	setcap cap_perfmon=+ep /usr/bin/intel_gpu_top
}
